config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html
get 'cosmosys/:id/menu', :to => 'cosmosys#menu'
get 'cosmosys/:id/tree', :to => 'cosmosys#tree'
get 'cosmosys/:id/treeview', :to => 'cosmosys#treeview'
get 'cosmosys/:id', :to => 'cosmosys#show'

get 'cosmosys/:id/issues', :to => 'cosmosys_issues#index'
get 'cosmosys_issues/:id/dep_gv', :to => 'cosmosys_issues#dep_gv'
get 'cosmosys_issues/:id/hie_gv', :to => 'cosmosys_issues#hie_gv'
get 'cosmosys/:id/dep_gv', :to => 'cosmosys#dep_gv'
get 'cosmosys/:id/hie_gv', :to => 'cosmosys#hie_gv'

#post 'cosmosys/:id/tree', :to => 'cosmosys#tree'
post 'cosmosys/:id/treeview', :to => 'cosmosys#treeview_commit'
post 'cosmosys/:id/up', :to => 'cosmosys#up'
post 'cosmosys/:id/down', :to => 'cosmosys#down'

post 'cosmosys/convert_to/:format/:project/:swp/:swptitle/:code/:title', :to => 'cosmosys#convert_to'

app/controllers/cosmosys_controller.rb
class CosmosysController < ApplicationController
  before_action :find_this_project
  # TODO: Understand how I could re-enable the "authorize" on dep_gv and hie_gv in this controller
  # but I was not able to do the same in cosmosys_issues_controller
  before_action :authorize, :except => [:find_this_project, :treeview,:treeview_commit, :convert_to]#,:dep_gv,:hie_gv]
  skip_before_action :verify_authenticity_token, only: [:convert_to]
  skip_before_action :check_if_login_required, only: [:treeview, :treeview_commit]

  @@tmpdir = './tmp/csys_plugin/'

  def dep_gv
    splitted_url = request.fullpath.split('/cosmosys')
    root_url = request.base_url+splitted_url[0]
    dg,hg = @project.csys.calculate_graphs(root_url)

    # Prefer early return to avoid over-indentation
    return unless dg != nil

    respond_to do |format|  ## Add this
      format.svg {render :inline => dg.output(:svg => String)}
      format.gv {render :inline => dg.to_s}
    end
  end

  def hie_gv
    splitted_url = request.fullpath.split('/cosmosys')
    root_url = request.base_url+splitted_url[0]
    dg,hg = @project.csys.calculate_graphs(root_url)

    # Prefer early return to avoid over-indentation
    return unless hg != nil

    respond_to do |format|  ## Add this
      format.svg {render :inline => hg.output(:svg => String)}
      format.gv {render :inline => hg.to_s}
    end
  end

  def menu
  end

  def show
    require 'json'

    # Get the user, either from the key or from the current user
    u = (params[:key] != nil) ? User.find_by_api_key(params[:key]) : User.current

    # Block access if the user is not allowed to see the project
    raise ::Unauthorized unless u.allowed_to?(:csys_treeview, @project)

    # Do nothing if the request is not a GET
    return unless request.get?

    respond_to do |format|
      format.html {
        # calculate
        @key = User.current.api_key
        @treeviewpath = "/cosmosys/"+@project.identifier+"/treeview"
      }

      format.json {
        treedata = []
        is_project = @issue ? false : true

        if (@issue) then
          thisnodeid = params[:issue_id]
        else
          res = @project.issues.where(:parent => nil).limit(1)
          thisnodeid = (res.size > 0) ? res.first.id : nil
        end

        thisnode = Issue.find(thisnodeid) unless thisnodeid == nil

        splitted_url = request.fullpath.split('/cosmosys')
        root_url = splitted_url[0]

        tree_node = create_tree(thisnode,root_url,is_project,@project,u.api_key)

        treedata << tree_node

        ActiveSupport.escape_html_entities_in_json = false
        render json: treedata
        ActiveSupport.escape_html_entities_in_json = true
      }
    end
  end

  def up
    @issue.csys.chapter_order -= 1.1
    @issue.csys.save
    @issue.csys.update_cschapter
    @issue.reenumerate_group
    redirect_to :action => 'show', :method => :get, :id => @project.id
  end

  def down
    @issue.csys.chapter_order += 1.1
    @issue.csys.save
    @issue.csys.update_cschapter
    @issue.reenumerate_group
    redirect_to :action => 'show', :method => :get, :id => @project.id
  end

  def translate_rel(is_dir_to,reltype)
    return reltype unless is_dir_to

    return "blocked by" if reltype == "blocks"

    return "follows" if reltype == "precedes"

    return reltype
  end

  private def create_project_tree(current_issue, root_url, thisproject, thiskey)
    issue_url = root_url + '/projects/' + thisproject.identifier
    issue_new_url = root_url + '/projects/' + thisproject.identifier + '/issues/new'
    cfprefixvalue = thisproject.code
    childrentypevector = thisproject.trackers.map{|t| t.name}

    # TODO: CHANGE THESE PATCHES BY A CALLBACK OR SOME PROPERTY, SO COSMOSYS DOES NOT KNOW ANYTHING ABOUT CSYSREQ
    childrentypevector += ["rqInfo","rqComplex","rqOpt","rqMech","rqHw","rqSw"] if childrentypevector.include?("rq")

    infobox = [
      ["Project:"],
      [thisproject.name,"/projects/"+thisproject.identifier,"link"],
      [thisproject.description],
    ]

    tree_node = {
      'title':  cfprefixvalue + ". " + thisproject.identifier  + ": " + thisproject.name,
      'subtitle': thisproject.description,
      'expanded': true,
      'id': thisproject.id.to_s,
      'return_url': root_url+'/cosmosys/'+thisproject.id.to_s+'/treeview.json'+'?key='+thiskey,
      'issue_show_url': issue_url+'?key='+thiskey,
      'issue_new_url': issue_new_url+'?key='+thiskey,
      'issue_edit_url': issue_url+"/edit"+'?key='+thiskey,
      'leaf': childrentypevector.size <= 0,
      'nodetype': "project",
      'childrentype': childrentypevector,
      'info': infobox,
      'children': []
    }

    childrenitems = thisproject.issues.where(:parent => nil).sort_by {|obj| obj.csys.chapter_order}

    childrenitems = thisproject.issues.select { |n| n.parent.project != thisproject } if childrenitems.size == 0

    childrenitems.each {|c| tree_node[:children] << create_tree(c,root_url,false,thisproject,thiskey) if c.csys.shall_report}

    thisproject.csys.update_cschapters

    return tree_node
  end

  private def create_nonproject_tree(current_issue, root_url, thisproject, thiskey)
    issue_url = root_url + '/issues/' + current_issue.id.to_s
    issue_new_url = root_url + '/projects/' + thisproject.identifier + '/issues/new?issue[parent_issue_id]=' + current_issue.id.to_s + '&issue[tracker_id]=' + "Feature"
    cftitlevalue = current_issue.subject
    cfchapterstring = current_issue.chapter_str
    childrentypevector = CosmosysIssue.get_childrentype(current_issue,current_issue.tracker)
    if current_issue.tracker.name != "rq" then
      childrentypevector += ["rqInfo","rqComplex","rqOpt","rqMech","rqHw","rqSw"] if childrentypevector.include?("rq")
    end
    currentnodetype = CosmosysIssue.get_nodetype(current_issue,current_issue.tracker)

    infobox = [
      [currentnodetype+": "+current_issue.csys.identifier],
      [current_issue.description],
    ]

    if current_issue.relations_to.size > 0 then
      infobox += [["*** Incoming relations ***"]]
      current_issue.relations_to.each{|r|
        infobox += [["<- "+translate_rel(true,r.relation_type)+" '"+r.issue_from.subject+"'","/issues/"+r.issue_from_id.to_s,r.issue_from.csys.identifier]]
      }
    end

    if current_issue.relations_from.size > 0 then
      infobox += [["*** Outgoing relations ***"]]
      current_issue.relations_from.each{|r|
        infobox += [["-> "+translate_rel(false,r.relation_type)+" '"+r.issue_to.subject+"'","/issues/"+r.issue_to_id.to_s,r.issue_to.csys.identifier]]
      }
    end

    if (current_issue.children.size > 0) then
      titlestring = cfchapterstring + " : " + cftitlevalue
    else
      # TODO: CHANGE THESE PATCHES BY A CALLBACK OR SOME PROPERTY, SO COSMOSYS DOES NOT KNOW ANYTHING ABOUT CSYSREQ
      if currentnodetype == "rqInfo" or current_issue.tracker.name == "csInfo" then
        titlestring = cfchapterstring + " " + cftitlevalue
      else
        titlestring = cfchapterstring + " " + current_issue.csys.get_identifier  + ": " + cftitlevalue
      end
    end

    tree_node = {
      'title':  titlestring,
      'subtitle': current_issue.description,
      'expanded': true,
      'id': current_issue.id.to_s,
      'return_url': root_url+'/cosmosys/'+thisproject.id.to_s+'/treeview.json?issue_id='+current_issue.id.to_s+'?key='+thiskey,
      'issue_show_url': issue_url+'?key='+thiskey,
      'issue_new_url': issue_new_url+'?key='+thiskey,
      'issue_edit_url': issue_url+"/edit"+'?key='+thiskey,
      'leaf': childrentypevector.size <= 0,
      'nodetype': currentnodetype,
      'childrentype': childrentypevector,
      'info': infobox,
      'children': []
    }

    childrenitems = current_issue.children.sort_by {|obj| obj.csys.chapter_order}

    childrenitems.each {|c| tree_node[:children] << create_tree(c,root_url,false,thisproject,thiskey) if c.csys.shall_report}

    return tree_node
  end

  def create_tree(current_issue, root_url, is_project, thisproject, thiskey)
    return is_project ?
      create_project_tree(current_issue, root_url, thisproject, thiskey) :
      create_nonproject_tree(current_issue, root_url, thisproject, thiskey)
  end

  def treeview
    require 'json'

    # Get the user, either from the key or from the current user
    u = (params[:key] != nil) ? User.find_by_api_key(params[:key]) : User.current

    # Block access if the user is not allowed to see the project
    raise ::Unauthorized unless u != nil
    raise ::Unauthorized unless u.class.name == "User" || params[:key] != nil
    raise ::Unauthorized unless u.class.name == "User" || params[:key] != ""
    raise ::Unauthorized unless u.allowed_to?(:csys_treeview, @project)

    # Do nothing if the request is not a GET
    return unless request.get?

    respond_to do |format|
      format.html {
        # calculate
        puts("key")
        @key = User.current.api_key
        puts(@key)
        splitted_url = request.fullpath.split('/cosmosys')
        root_url = splitted_url[0]
        @treeviewpath = root_url+"/cosmosys/"+@project.identifier+"/treeview"
      }

      format.json {
        treedata = []
        is_project = @issue ? false : true

        if (@issue) then
          thisnodeid = params[:issue_id]
        else
          res = @project.issues.where(:parent => nil).limit(1)
          thisnodeid = (res.size > 0) ? res.first.id : nil
        end

        thisnode = Issue.find(thisnodeid) if thisnodeid != nil

        splitted_url = request.fullpath.split('/cosmosys')
        root_url = splitted_url[0]

        tree_node = create_tree(thisnode,root_url,is_project,@project,u.api_key)

        treedata << tree_node

        ActiveSupport.escape_html_entities_in_json = false
        render json: treedata
        ActiveSupport.escape_html_entities_in_json = true
      }
    end
  end

  def treeview_commit
    # Get the user, either from the key or from the current user

app/helpers/cosmosys_helper.rb
module CosmosysHelper
end

app/views/cosmosys/excluded_titles/_applicable_documents.html.erb
<div class="apldocstable">
  <table>
    <thead>
      <tr>
        <th>Subject</th>
        <th>Description</th>
      </tr>
    </thead>
    <tbody>
<% item.children.sort_by{|obj| obj.chapter_order}.each{|i| %>
      <tr>
        <td><%= link_to i.subject, issue_path(i.id) %></td>
        <td><%= textilizable(i.description) %></td>
      </tr>
<% } %>
    </tbody>
  </table>
</div>

app/views/cosmosys/excluded_titles/_compliance_documents.html.erb
<div class="compdocstable">
  <table>
    <thead>
      <tr>
        <th>Subject</th>
        <th>Description</th>
      </tr>
    </thead>
    <tbody>
<% item.children.sort_by{|obj| obj.chapter_order}.each{|i| %>
      <tr>
        <td><%= link_to i.subject, issue_path(i.id) %></td>
        <td><%= textilizable(i.description) %></td>
      </tr>
<% } %>
    </tbody>
  </table>
</div>

app/views/cosmosys/excluded_titles/_compliance_matrix.html.erb
<%
    ###########################################################################
    #                                                                         #
    # TODO: This should not be in cosmosys, but in cosmosys_req.              #
    #       We need a callback.                                               #
    #                                                                         #
    rqstatefield = IssueCustomField.find_by_name('rqComplanceState')          #
    rqjustiffield = IssueCustomField.find_by_name('rqComplianceJustif')       #
    rqrefdocfield = IssueCustomField.find_by_name('rqComplianceDocs')         #
    rqverif = IssueCustomField.find_by_name('rqVerif')                        #
    rqverifdescr = IssueCustomField.find_by_name('rqVerifDescr')                        #
    #                                                                         #
    ###########################################################################
%>
<div class="compliancematrix">
  <table>
    <thead>
      <tr>
        <th>csID</th>
        <th>Chapter</th>
        <th>Title</th>
        <th>Verif. type</th>
        <th>Verif. description</th>
        <th>Sta of Compl</th>
        <th>Justification</th>
        <th>Compliance Docs</th>
      </tr>
    </thead>
    <tbody>
<% @project.issues.each{|i| %>
      <tr>
<%
puts i.subject
if (i.csys.shall_draw) and not i.csys.is_chapter? then
    compl_rqverif = i.custom_field_values.select{|a| a.custom_field_id == rqverif.id }.first
    compl_rqverifdescr = i.custom_field_values.select{|a| a.custom_field_id == rqverifdescr.id }.first
    compl_state = i.custom_field_values.select{|a| a.custom_field_id == rqstatefield.id }.first
    compl_justif = i.custom_field_values.select{|a| a.custom_field_id == rqjustiffield.id }.first
    compl_refdocs = i.custom_field_values.select{|a| a.custom_field_id == rqrefdocfield.id }.first
%>
        <td><%= link_to i.csys.get_identifier, issue_path(i.id) %></td>
        <td><%= i.csys.chapter_str %></td>
        <td><%= i.subject %></td>
        <td><%= compl_rqverif != nil ? textilizable(compl_rqverif.value.join(", ")) : "" %></td>
        <td><%= compl_rqverifdescr != nil ? textilizable(compl_rqverifdescr.value.to_s) : "" %></td>
        <td><%= compl_state != nil ? compl_state.value.to_s : "" %></td>
        <td><%= compl_justif != nil ? textilizable(compl_justif.value.to_s) : "" %></td>
        <td>
          <div><%= compl_refdocs != nil and compl_refdocs.value != nil ? textilizable(i.csys.get_compdocs_table) : "" %></div>
        </td>
<%
end
%>
      </tr>
<% } %>
    </tbody>
  </table>
</div>

app/views/cosmosys/excluded_titles/_deleted_requirements.html.erb
<div class="apldocstable">
  <table>
    <thead>
      <tr>
        <th>csID</th>
        <th>Title</th>
      </tr>
    </thead>
    <tbody>
<% item.children.sort_by{|obj| obj.chapter_order}.each{|i| %>
      <tr>
        <td><%= link_to i.csys.identifier, issue_path(i.id) %></td>
        <td><%= i.subject %></td>
      </tr>
<% } %>
    </tbody>
  </table>
</div>

app/views/cosmosys/excluded_titles/_list_of_abbreviations.erb
<div class="apldocstable">
  <table>
    <thead>
      <tr>
        <th>Subject</th>
        <th>Description</th>
      </tr>
    </thead>
    <tbody>
<% item.children.sort_by{|obj| obj.chapter_order}.each{|i| %>
      <tr>
        <td><%= link_to i.subject, issue_path(i.id) %></td>
        <td><%= textilizable(i.description) %></td>
      </tr>
<% } %>
    </tbody>
  </table>
</div>

app/views/cosmosys/excluded_titles/_reference_documents.html.erb
<div class="refdocstable">
  <table>
    <thead>
      <tr>
        <th>Subject</th>
        <th>Description</th>
      </tr>
    </thead>
    <tbody>
<% item.children.sort_by{|obj| obj.chapter_order}.each{|i| %>
      <tr>
        <td><%= link_to i.subject, issue_path(i.id) %></td>
        <td><%= textilizable(i.description) %></td>
      </tr>
<% } %>
    </tbody>
  </table>
</div>

app/views/cosmosys/excluded_titles/_units.erb
<div class="apldocstable">
  <table>
    <thead>
      <tr>
        <th>Subject</th>
        <th>Description</th>
      </tr>
    </thead>
    <tbody>
<% item.children.sort_by{|obj| obj.chapter_order}.each{|i| %>
      <tr>
        <td><%= link_to i.subject, issue_path(i.id) %></td>
        <td><%= textilizable(i.description) %></td>
      </tr>
<% } %>
    </tbody>
  </table>
</div>